**NUMPY HW**

Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [9]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])


In [10]:
VerticalStack = np.vstack((A, B))

print(VerticalStack)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
HorizontalStack = np.hstack((A,B))

print(HorizontalStack)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Find common elements between A and B. [Hint: Intersection of two sets]


In [14]:
import numpy as np

A = np.array([1, 2, 3, 4, 5])
B = np.array([4, 5, 6, 7, 8])

common_elements = np.intersect1d(A, B)
print(common_elements)


[4 5]


Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [16]:
import numpy as np

A = np.array([2, 5, 6, 9, 10, 12, 3, 8])

mask = (A >= 5) & (A <= 10)
print(mask)


[False  True  True  True  True False False  True]


Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [17]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Filter rows where petal length > 1.5 and sepal length < 5.0
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print(filtered_rows)


[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


**HW Questions (Pandas):**

From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [18]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Filter 'Manufacturer', 'Model', and 'Type' for every 20th row
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

print(filtered_df)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


Replace missing values in Min.Price and Max.Price columns with their respective mean. (I dont understand)


In [23]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Replace missing values in Min.Price and Max.Price with their respective means
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

# Check that no NaN values remain
print(df[['Min.Price', 'Max.Price']].isnull().sum())


Min.Price    0
Max.Price    0
dtype: int64


How to get the rows of a dataframe with row sum > 100?

In [24]:
import pandas as pd
import numpy as np

# Step 1: Create a random DataFrame (15 rows × 4 columns)
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print("Original DataFrame:\n", df.head(), "\n")

# Step 2: Compute row sums
df['RowSum'] = df.sum(axis=1)

# Step 3: Filter rows where row sum > 100
filtered_df = df[df['RowSum'] > 100]

print("Rows with sum > 100:\n", filtered_df)


Original DataFrame:
     0   1   2   3
0  16  35  31  23
1  33  10  28  14
2  21  30  38  10
3  10  11  35  26
4  14  28  25  27 

Rows with sum > 100:
      0   1   2   3  RowSum
0   16  35  31  23     105
14  29  21  28  26     104
